import type { ITerminalInitOnlyOptions, ITerminalOptions } from '@xterm/xterm';

export const TERMINAL_PRESENTATION_OPTIONS = {
  allowProposedApi: true,
  cursorBlink: true,
  cursorStyle: 'bar',
  cursorInactiveStyle: 'outline',
  cursorWidth: 2,
  drawBoldTextInBrightColors: true,
  fontFamily:
    "'SFMono-Regular', 'SF Mono', 'Cascadia Code', 'Liberation Mono', Menlo, monospace",
  fontSize: 14,
  fontWeight: '400',
  fontWeightBold: '600',
  letterSpacing: 0.2,
  lineHeight: 1.3,
  minimumContrastRatio: 4.5,
  screenReaderMode: true,
  scrollback: 5_000,
  theme: {
    background: '#080c12',
    foreground: '#d8e2ef',
    cursor: '#6ee7b7',
    cursorAccent: '#080c12',
    selectionBackground: '#334155aa',
    selectionInactiveBackground: '#25324780',
    black: '#0f172a',
    red: '#fb7185',
    green: '#6ee7b7',
    yellow: '#fbbf24',
    blue: '#60a5fa',
    magenta: '#c084fc',
    cyan: '#22d3ee',
    white: '#e2e8f0',
    brightBlack: '#64748b',
    brightRed: '#fda4af',
    brightGreen: '#a7f3d0',
    brightYellow: '#fde68a',
    brightBlue: '#93c5fd',
    brightMagenta: '#d8b4fe',
    brightCyan: '#67e8f9',
    brightWhite: '#f8fafc',
  },
} satisfies ITerminalOptions & ITerminalInitOnlyOptions;
