import type { ITerminalInitOnlyOptions, ITerminalOptions } from '@xterm/xterm';

export const TERMINAL_PRESENTATION_OPTIONS = {
  allowProposedApi: true,
  cursorBlink: true,
  cursorStyle: 'bar',
  cursorInactiveStyle: 'outline',
  cursorWidth: 2,
  drawBoldTextInBrightColors: true,
  fontFamily:
    "'SFMono-Regular', 'SF Mono', 'Cascadia Code', 'Liberation Mono', Menlo, monospace",
  fontSize: 14,
  fontWeight: '400',
  fontWeightBold: '600',
  letterSpacing: 0.2,
  lineHeight: 1.3,
  minimumContrastRatio: 4.5,
  screenReaderMode: true,
  scrollback: 5_000,
  theme: {
    background: '#090c10',
    foreground: '#dce2e7',
    cursor: '#73d9ad',
    cursorAccent: '#090c10',
    selectionBackground: '#34433fbb',
    selectionInactiveBackground: '#27332f88',
    black: '#11161b',
    red: '#ef8d98',
    green: '#73d9ad',
    yellow: '#e8b96a',
    blue: '#77bdfb',
    magenta: '#c39be8',
    cyan: '#6ac8d7',
    white: '#dce2e7',
    brightBlack: '#697580',
    brightRed: '#f6a9b1',
    brightGreen: '#9aebc7',
    brightYellow: '#f0cf91',
    brightBlue: '#9dd0ff',
    brightMagenta: '#d8b8f2',
    brightCyan: '#94dce6',
    brightWhite: '#f4f6f8',
  },
} satisfies ITerminalOptions & ITerminalInitOnlyOptions;
